### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by mariorodriguespt** [daem-on/fwf#7]
The `README.md` lacks instructions on how to install locally and also running locally for development.

**Comment by Unicorndy** [comment]
Hi, same here, would really appreciate if instructions for running locally are included.

**Comment by daem-on** [comment]
Instructions added in 2548bd46d840cc569b156b50da6e187b436b9387. It's now avalable at https://github.com/daem-on/fwf#running-and-building-from-source.
